---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '4'
    k8s.kuboard.cn/ingress: 'false'
    k8s.kuboard.cn/service: none
    k8s.kuboard.cn/workload: web-chineseocr
  creationTimestamp: '2020-08-24T03:02:43Z'
  generation: 4
  labels:
    k8s.kuboard.cn/layer: web
    k8s.kuboard.cn/name: web-chineseocr
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:k8s.kuboard.cn/ingress': {}
            'f:k8s.kuboard.cn/service': {}
            'f:k8s.kuboard.cn/workload': {}
          'f:labels':
            .: {}
            'f:k8s.kuboard.cn/layer': {}
            'f:k8s.kuboard.cn/name': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector':
            'f:matchLabels':
              .: {}
              'f:k8s.kuboard.cn/layer': {}
              'f:k8s.kuboard.cn/name': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:k8s.kuboard.cn/layer': {}
                'f:k8s.kuboard.cn/name': {}
            'f:spec':
              'f:containers':
                'k:{"name":"chineseocr"}':
                  .: {}
                  'f:command': {}
                  'f:image': {}
                  'f:imagePullPolicy': {}
                  'f:lifecycle': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8080,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:hostPort': {}
                      'f:protocol': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsConfig': {}
              'f:dnsPolicy': {}
              'f:imagePullSecrets':
                .: {}
                'k:{"name":"hub.suomitek.com"}':
                  .: {}
                  'f:name': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext':
                .: {}
                'f:seLinuxOptions': {}
              'f:terminationGracePeriodSeconds': {}
      manager: Mozilla
      operation: Update
      time: '2020-08-24T03:12:03Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            'k:{"type":"Progressing"}':
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
      manager: kube-controller-manager
      operation: Update
      time: '2020-08-24T03:12:05Z'
  name: web-chineseocr
  namespace: polyaxon
  resourceVersion: '1526385'
  selfLink: /apis/apps/v1/namespaces/polyaxon/deployments/web-chineseocr
  uid: 4114702f-5134-4e88-84f7-f668c57f19f6
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: web
      k8s.kuboard.cn/name: web-chineseocr
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s.kuboard.cn/layer: web
        k8s.kuboard.cn/name: web-chineseocr
    spec:
      containers:
        - command:
            - /bin/bash
            - '-ce'
            - tail -f /dev/null
          image: 'hub.suomitek.com:8002/ai/chineseocr:latest'
          imagePullPolicy: Always
          lifecycle: {}
          name: chineseocr
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: hub.suomitek.com
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seLinuxOptions: {}
      terminationGracePeriodSeconds: 30


