---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
    k8s.kuboard.cn/ingress: 'false'
    k8s.kuboard.cn/service: none
    k8s.kuboard.cn/workload: web-chineseocr
  creationTimestamp: '2020-08-24T02:02:21Z'
  generation: 1
  labels:
    k8s.kuboard.cn/layer: web
    k8s.kuboard.cn/name: web-chineseocr
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata': {}
        'f:spec':
          'f:selector': {}
          'f:strategy': {}
          'f:template':
            'f:metadata': {}
            'f:spec':
              'f:containers': {}
              'f:imagePullSecrets': {}
      manager: Mozilla
      operation: Update
      time: '2020-08-24T02:02:21Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata': {}
        'f:status':
          'f:conditions': {}
      manager: kube-controller-manager
      operation: Update
      time: '2020-08-24T02:02:21Z'
  name: web-chineseocr
  namespace: polyaxon
  resourceVersion: '1511876'
  selfLink: /apis/apps/v1/namespaces/polyaxon/deployments/web-chineseocr
  uid: eb8e7b14-72a9-4104-a13b-fbfb18933cbd
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: web
      k8s.kuboard.cn/name: web-chineseocr
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s.kuboard.cn/layer: web
        k8s.kuboard.cn/name: web-chineseocr
    spec:
      containers:
        - image: 'hub.suomitek.com:8002/ai/chineseocr:latest'
          imagePullPolicy: Always
          name: chineseocr
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: hub.suomitek.com
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
status:
  conditions:
    - lastTransitionTime: '2020-08-24T02:02:21Z'
      lastUpdateTime: '2020-08-24T02:02:21Z'
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: 'False'
      type: Available
    - lastTransitionTime: '2020-08-24T02:02:21Z'
      lastUpdateTime: '2020-08-24T02:02:21Z'
      message: ReplicaSet "web-chineseocr-6785b46b7" is progressing.
      reason: ReplicaSetUpdated
      status: 'True'
      type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1


