---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '4'
    k8s.kuboard.cn/ingress: 'false'
    k8s.kuboard.cn/service: none
    k8s.kuboard.cn/workload: web-chineseocr
  creationTimestamp: '2020-08-24T03:02:43Z'
  generation: 4
  labels:
    k8s.kuboard.cn/layer: web
    k8s.kuboard.cn/name: web-chineseocr
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata': {}
        'f:spec':
          'f:selector': {}
          'f:strategy': {}
          'f:template':
            'f:metadata': {}
            'f:spec':
              'f:containers':
                'k:{"name":"chineseocr"}':
                  'f:ports': {}
              'f:imagePullSecrets': {}
      manager: Mozilla
      operation: Update
      time: '2020-08-24T03:12:03Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata': {}
        'f:status':
          'f:conditions': {}
      manager: kube-controller-manager
      operation: Update
      time: '2020-08-24T03:12:05Z'
  name: web-chineseocr
  namespace: polyaxon
  resourceVersion: '1526385'
  selfLink: /apis/apps/v1/namespaces/polyaxon/deployments/web-chineseocr
  uid: 4114702f-5134-4e88-84f7-f668c57f19f6
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: web
      k8s.kuboard.cn/name: web-chineseocr
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s.kuboard.cn/layer: web
        k8s.kuboard.cn/name: web-chineseocr
    spec:
      containers:
        - command:
            - /bin/bash
            - '-ce'
            - tail -f /dev/null
          image: 'hub.suomitek.com:8002/ai/chineseocr:latest'
          imagePullPolicy: Always
          name: chineseocr
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: hub.suomitek.com
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2020-08-24T03:10:31Z'
      lastUpdateTime: '2020-08-24T03:10:31Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2020-08-24T03:02:43Z'
      lastUpdateTime: '2020-08-24T03:12:05Z'
      message: ReplicaSet "web-chineseocr-7fcbdcbb" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1


