env:
  open:
    #开启api
    DISABLE_API: false
    ALLOW_OVERWRITE: true
  secret:
    BASIC_AUTH_USER: myuser
    BASIC_AUTH_PASS: mypass
resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 80m
    memory: 64Mi
persistence:
  enabled: true
  size: 10Gi
  storageClass: "managed-nfs-storage"
