
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: suomitek-helm
  name: web-chartmuseum
  annotations:
    k8s.kuboard.cn/workload: web-chartmuseum
    deployment.kubernetes.io/revision: '2'
    k8s.kuboard.cn/ingress: 'true'
    k8s.kuboard.cn/service: NodePort
  labels:
    k8s.kuboard.cn/layer: web
    k8s.kuboard.cn/name: web-chartmuseum
spec:
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: web
      k8s.kuboard.cn/name: web-chartmuseum
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        k8s.kuboard.cn/layer: web
        k8s.kuboard.cn/name: web-chartmuseum
    spec:
      securityContext:
        seLinuxOptions: {}
      imagePullSecrets: []
      restartPolicy: Always
      initContainers: []
      containers:
        - image: 'chartmuseum/chartmuseum:latest'
          imagePullPolicy: Always
          name: chartmuseum
          volumeMounts:
            - name: charts
              mountPath: /charts
          resources:
            limits:
            requests:
          env:
            - name: STORAGE
              value: local
            - name: STORAGE_LOCAL_ROOTDIR
              value: /charts
          lifecycle: {}
          ports:
            - containerPort: 8080
              protocol: TCP
      volumes:
        - name: charts
          persistentVolumeClaim:
            claimName: charts
      dnsPolicy: ClusterFirst
      dnsConfig: {}
      terminationGracePeriodSeconds: 30
  progressDeadlineSeconds: 600
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  replicas: 1

---
apiVersion: v1
kind: Service
metadata:
  namespace: suomitek-helm
  name: web-chartmuseum
  annotations:
    k8s.kuboard.cn/workload: web-chartmuseum
  labels:
    k8s.kuboard.cn/layer: web
    k8s.kuboard.cn/name: web-chartmuseum
spec:
  selector:
    k8s.kuboard.cn/layer: web
    k8s.kuboard.cn/name: web-chartmuseum
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: 85mmj3
      nodePort: 30821
  sessionAffinity: None

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: suomitek-helm
  name: web-chartmuseum
  annotations:
    k8s.kuboard.cn/workload: web-chartmuseum
  labels:
    k8s.kuboard.cn/layer: web
    k8s.kuboard.cn/name: web-chartmuseum
spec:
  rules:
    - host: helm.yongchehang.com
      http:
        paths:
          - path: /
            backend:
              serviceName: web-chartmuseum
              servicePort: 85mmj3

